apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
  namespace: database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: proxmox
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/"
      endpointURL: "http://10.9.0.52:8333"
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-s3-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 2
    retentionPolicy: "30d"
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-credentials
      postInitSQL:
        - CREATE ROLE linkwarden LOGIN
        - CREATE DATABASE linkwarden OWNER linkwarden
  managed:
    roles:
      - name: linkwarden
        ensure: present
        login: true
        passwordSecret:
          name: linkwarden-db-credentials
  enableSuperuserAccess: false
