apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        ACCESS_KEY_ID: "{{ .accessKey }}"
        ACCESS_SECRET_KEY: "{{ .secretKey }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: kubernetes/s3
        property: access-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: secretKey
      remoteRef:
        key: kubernetes/s3
        property: secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
