apiVersion: v1
kind: Service
metadata:
  name: huntarr
  namespace: external-services
spec:
  type: ExternalName
  externalName: 10.9.0.50
  ports:
    - name: http
      port: 9705
      targetPort: 9705
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huntarr-tls
  namespace: external-services
  annotations:
    avp.kubernetes.io/path: "secret/data/kubernetes/config"
spec:
  secretName: huntarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - huntarr.<domain>
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr
  namespace: external-services
  annotations:
    avp.kubernetes.io/path: "secret/data/kubernetes/config"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`huntarr.<domain>`)
      kind: Rule
      services:
        - name: huntarr
          port: 9705
  tls:
    secretName: huntarr-tls
