apiVersion: v1
kind: Service
metadata:
  name: lodz
  namespace: external-services
spec:
  type: ExternalName
  externalName: 10.23.0.68
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lodz-tls
  namespace: external-services
  annotations:
    avp.kubernetes.io/path: "secret/data/kubernetes/config"
spec:
  secretName: lodz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - lodz.<domain>
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lodz
  namespace: external-services
  annotations:
    avp.kubernetes.io/path: "secret/data/kubernetes/config"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lodz.<domain>`)
      kind: Rule
      services:
        - name: lodz
          port: 8006
          scheme: https
  tls:
    secretName: lodz-tls
