apiVersion: v1
kind: Service
metadata:
  name: torrent
  namespace: external-services
spec:
  type: ExternalName
  externalName: 10.9.0.50
  ports:
    - name: http
      port: 8085
      targetPort: 8085
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torrent-tls
  namespace: external-services
  annotations:
    avp.kubernetes.io/path: "secret/data/kubernetes/config"
spec:
  secretName: torrent-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - torrent.<domain>
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: torrent
  namespace: external-services
  annotations:
    avp.kubernetes.io/path: "secret/data/kubernetes/config"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`torrent.<domain>`)
      kind: Rule
      services:
        - name: torrent
          port: 8085
  tls:
    secretName: torrent-tls
