apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      targetRevision: 4.13.3
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/nfs-csi/values.yaml

    - repoURL: https://github.com/bartek412/homelab.git
      targetRevision: main
      ref: values

    # NFS StorageClass
    - repoURL: https://github.com/bartek412/homelab.git
      targetRevision: main
      path: kubernetes/infrastructure/nfs-csi/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
