apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-config-volsync-secret
  namespace: technitium
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: technitium-config-volsync-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"
        RESTIC_REPOSITORY: "s3:http://10.9.0.52:8333/volsync-backups/technitium-config"
  data:
    - secretKey: resticPassword
      remoteRef:
        key: kubernetes/volsync
        property: restic-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: accessKey
      remoteRef:
        key: kubernetes/s3
        property: access-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: secretKey
      remoteRef:
        key: kubernetes/s3
        property: secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
