apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
  namespace: karakeep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: kubernetes/karakeep
        property: nextauth-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: meili-master-key
      remoteRef:
        key: kubernetes/karakeep
        property: meili-master-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
