apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .postgresPassword }}"
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: kubernetes/authentik
        property: postgres-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
