apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Helm chart
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/metallb/values.yaml

    # Values from Git
    - repoURL: https://github.com/bartek412/homelab.git
      targetRevision: main
      ref: values

    # Raw manifests (IPAddressPool, L2Advertisement)
    - repoURL: https://github.com/bartek412/homelab.git
      targetRevision: main
      path: kubernetes/infrastructure/metallb/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
