apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status

  sources:
    - repoURL: https://github.com/bartek412/homelab.git
      targetRevision: main
      path: kubernetes/infrastructure/shared-postgres/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
