deployment:
  replicas: 1

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-external

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    ingressClass: traefik-external
  kubernetesIngress:
    enabled: true
    ingressClass: traefik-external

ports:
  web:
    port: 8000
    exposedPort: 80
    expose:
      default: true
  websecure:
    port: 8443
    exposedPort: 443
    expose:
      default: true

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.9.0.231"

globalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.websecure.tls=true"
