apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkwarden-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: kubernetes/linkwarden
        property: nextauth-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: postgres-password
      remoteRef:
        key: kubernetes/linkwarden
        property: postgres-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: database-url
      remoteRef:
        key: kubernetes/linkwarden
        property: database-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: nextauth-url
      remoteRef:
        key: kubernetes/linkwarden
        property: nextauth-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
